package jp.n05ym.minestatsviewer;

final class WebPages {
    private WebPages() {}

    static final String OVERLAY = """
<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<style>
*{box-sizing:border-box}html,body{margin:0;background:transparent;color:var(--text);font-family:var(--ui-font);font-optical-sizing:auto;font-synthesis:none;text-rendering:geometricPrecision}.panel{margin:2px;padding:var(--padding);width:max-content;min-width:200px;border:var(--border) solid var(--accent);background:color-mix(in srgb,var(--background) var(--opacity),transparent);border-radius:var(--radius)}.panel[hidden]{display:none}h1{margin:0 0 8px;padding-bottom:13px;border-bottom:5px solid var(--accent);font-family:var(--display-font);font-size:var(--title-size);font-weight:700;line-height:1.05;letter-spacing:-.02em;color:var(--title-color)}.grid{display:grid;grid-template-columns:repeat(var(--columns),var(--item-width));column-gap:var(--column-gap)}.row{display:grid;grid-template-columns:calc(var(--icon-size) + 6px) minmax(50px,1fr) auto;column-gap:var(--item-gap);align-items:center;width:var(--item-width);padding:var(--row-gap) 0;border-top:1px solid color-mix(in srgb,var(--text) 18%,transparent)}.grid .row:first-child,.grid.no-title.columns-1 .row:first-child,.grid.no-title.columns-2 .row:nth-child(-n+2),.grid.no-title.columns-3 .row:nth-child(-n+3),.grid.no-title.columns-4 .row:nth-child(-n+4){border-top:0}.row.no-label{grid-template-columns:calc(var(--icon-size) + 6px) auto;width:max-content;justify-content:start}.row.no-label .value{min-width:0;grid-template-columns:auto auto auto}.icon{width:var(--icon-size);height:var(--icon-size);object-fit:contain;image-rendering:pixelated}.emoji{font-size:calc(var(--icon-size) * .75);line-height:var(--icon-size);display:inline-block;width:var(--icon-size);height:var(--icon-size);text-align:center}.label{font-weight:550;font-size:var(--label-size);letter-spacing:.01em;color:var(--label-color)}.value{font-family:var(--number-font);font-variant-numeric:tabular-nums;white-space:nowrap;font-size:var(--value-size);font-weight:700;line-height:1;letter-spacing:-.02em;display:grid;grid-template-columns:minmax(0,1fr) auto var(--suffix-slot,0px);align-items:baseline;min-width:var(--value-width)}.prefix{text-align:right}.number{text-align:right}.suffix{text-align:left}.affix{font-family:var(--ui-font);font-weight:600;vertical-align:baseline;letter-spacing:0}.anim-color{animation:colorPulse var(--anim-duration) ease}.anim-pop{animation:pop var(--anim-duration) ease}.anim-glow{animation:glow var(--anim-duration) ease}@keyframes colorPulse{50%{color:var(--anim-color)}}@keyframes pop{50%{color:var(--anim-color);transform:scale(1.08)}}@keyframes glow{50%{color:var(--anim-color);text-shadow:0 0 12px var(--anim-color)}}
</style></head><body><main id="panel" class="panel" hidden><section id="view"><h1 id="title"></h1><div class="grid" id="grid"></div></section></main>
<script>
const PREVIEW=new URLSearchParams(location.search).has('preview');let config=null,last={},rendered='',failures=0;const fmt=new Intl.NumberFormat('ja-JP');
const FONT_PRESETS={modern:{ui:'"Noto Sans JP","Yu Gothic","Hiragino Sans",system-ui,sans-serif',display:'Bahnschrift,"Segoe UI Variable Display","Noto Sans JP",sans-serif',number:'Bahnschrift,"Segoe UI Variable Display","Noto Sans JP",sans-serif'},readable:{ui:'"BIZ UDPGothic","Noto Sans JP","Yu Gothic UI",sans-serif',display:'"BIZ UDPGothic","Noto Sans JP",sans-serif',number:'Bahnschrift,"BIZ UDPGothic",sans-serif'},serif:{ui:'"Noto Serif JP","Yu Mincho","Hiragino Mincho ProN",serif',display:'"Noto Serif JP","Yu Mincho","Hiragino Mincho ProN",serif',number:'Georgia,"Noto Serif JP",serif'},game:{ui:'"BIZ UDPGothic","Noto Sans JP",sans-serif',display:'Consolas,Bahnschrift,"BIZ UDPGothic",sans-serif',number:'Consolas,Bahnschrift,monospace'}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function icon(w){if(w.iconKind&&w.iconKind!=='none'&&w.iconId)return `<img class="icon" onerror="this.style.display='none';this.nextElementSibling.style.display='block'" src="/api/icon?kind=${encodeURIComponent(w.iconKind)}&id=${encodeURIComponent(w.iconId)}"><span class="emoji" style="display:none">${esc(w.emoji||'📊')}</span>`;return `<span class="emoji">${esc(w.emoji||'📊')}</span>`}
function calc(w,d){let source=d[w.source||'session']||{},vals=(w.terms||[]).map((t,i)=>{let v=t.prefix?Object.entries(source).filter(([k])=>k.startsWith(t.prefix)).reduce((a,[,n])=>a+n,0):(source[t.stat]||0);return{value:v*(Number(t.factor)||0),role:t.role||(i===0?'a':'b')}}),sum=vals.reduce((a,x)=>a+x.value,0),a=vals.filter(x=>x.role==='a').reduce((n,x)=>n+x.value,0),b=vals.filter(x=>x.role!=='a').reduce((n,x)=>n+x.value,0);if(w.operation==='ratio')return b?a/b*100:0;if(w.operation==='share')return sum?a/sum*100:0;if(w.operation==='remaining')return Math.max(0,(Number(w.target)||0)-sum);if(w.operation==='rate'){let ticks=d.session?.['minecraft:custom|minecraft:play_time']||0;return ticks?sum/(ticks/72000):0}return sum}
function format(n,w){if(w.format==='percent')return n.toFixed(1)+'%';if(w.format==='time'){let s=Math.floor(n/20),h=Math.floor(s/3600),m=Math.floor(s%3600/60);return `${h}:${String(m).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}return fmt.format(Math.round(n))}
function previewValue(w,i){if(w.format==='time')return 267100;if(w.format==='percent'||w.operation==='ratio'||w.operation==='share')return 24.8;if(w.operation==='remaining')return Math.min(Number(w.target)||100,37);if(w.operation==='rate')return 48;return 1284+i*137}
function renderCards(){let signature=JSON.stringify(config);if(signature===rendered)return;rendered=signature;let html='';(config.widgets||[]).filter(w=>w.visible!==false).forEach(w=>{let pre=w.prefixText||'',post=w.suffixText??w.suffix??'',hideLabel=w.labelVisible===false,valueColor=w.color||config.valueColor||config.textColor||'#2835f8';html+=`<div class="row${hideLabel?' no-label':''}" data-widget="${esc(w.id)}"><div>${icon(w)}</div>${hideLabel?'':`<span class="label">${esc(w.label)}</span>`}<span class="value" style="color:${esc(valueColor)};--anim-color:${esc(w.animationColor||config.accent||'#ff3d00')};--anim-duration:${Number(w.animationDuration)||450}ms"><span class="affix prefix" style="color:${esc(w.prefixColor||valueColor)};font-size:${Number(w.prefixSize)||14}px">${esc(pre)}</span><span class="number">0</span><span class="affix suffix" style="color:${esc(w.suffixColor||valueColor)};font-size:${Number(w.suffixSize)||14}px">${esc(post)}</span></span></div>`});grid.innerHTML=html;grid.className='grid columns-'+Math.max(1,Math.min(4,Number(config.columns)||1))+(config.showTitle===false?' no-title':'');requestAnimationFrame(()=>{let max=Math.max(0,...[...grid.querySelectorAll('.suffix')].map(x=>x.getBoundingClientRect().width));grid.style.setProperty('--suffix-slot',Math.ceil(max)+(max?4:0)+'px')})}
async function tick(){try{if(!config)config=await(await fetch('/api/config')).json();let d=PREVIEW?{connected:true,total:{},session:{}}:await(await fetch('/api/stats')).json();failures=0;panel.hidden=!d.connected;if(!d.connected)return;let s=document.documentElement.style,font=FONT_PRESETS[config.fontPreset]||FONT_PRESETS.modern;s.setProperty('--ui-font',font.ui);s.setProperty('--display-font',font.display);s.setProperty('--number-font',font.number);s.setProperty('--accent',config.accent||'#ff3d00');s.setProperty('--title-color',config.titleColor||'#11110f');s.setProperty('--label-color',config.labelColor||config.textColor||'#11110f');s.setProperty('--text',config.textColor||'#11110f');s.setProperty('--background',config.background||'#f4e9e1');s.setProperty('--opacity',(config.backgroundOpacity??96)+'%');s.setProperty('--columns',config.columns||1);s.setProperty('--padding',(config.panelPadding??24)+'px');s.setProperty('--row-gap',(config.itemGap??7)+'px');s.setProperty('--item-gap',(config.elementGap??12)+'px');s.setProperty('--column-gap',(config.columnGap??24)+'px');s.setProperty('--item-width',(config.itemWidth??460)+'px');s.setProperty('--value-width',(config.valueWidth??180)+'px');s.setProperty('--icon-size',(config.iconSize??44)+'px');s.setProperty('--title-size',(config.titleSize??42)+'px');s.setProperty('--label-size',(config.labelSize??24)+'px');s.setProperty('--value-size',(config.valueSize??42)+'px');s.setProperty('--radius',(config.radius??16)+'px');s.setProperty('--border',(config.borderWidth??0)+'px');title.textContent=config.title||'';title.hidden=config.showTitle===false;renderCards();let rows=[...grid.querySelectorAll('[data-widget]')];(config.widgets||[]).filter(w=>w.visible!==false).forEach((w,i)=>{let n=PREVIEW?previewValue(w,i):calc(w,d),changed=!PREVIEW&&last[w.id]!==undefined&&last[w.id]!==n,value=rows[i]?.querySelector('.value'),number=value?.querySelector('.number');last[w.id]=n;if(!number)return;number.textContent=format(n,w);if(changed&&w.animationEnabled!==false){let cls='anim-'+(w.animationType||'color');value.classList.remove('anim-color','anim-pop','anim-glow');void value.offsetWidth;value.classList.add(cls)}})}catch(e){if(++failures>4&&!PREVIEW)panel.hidden=true}}
setInterval(tick,250);setInterval(()=>config=null,1000);tick();
</script></body></html>
""";
}
